.syntax unified

.global mulmod
.type mulmod,%function
.align 2
mulmod:
    push {r4-r11, r14}

    // TODO: write your code here

    pop {r4-r11, pc}

.global butterfly
.type butterfly,%function
.align 2
butterfly:
    push {r4-r11, r14}

    // TODO: write your code here


    pop {r4-r11, pc}


.global nttlayer1
.type nttlayer1,%function
.align 2
nttlayer1:
    push {r4-r11, r14}

    // TODO: write your code here

    pop {r4-r11, pc}


.global ntt
.type ntt,%function
.align 2
ntt:
    push {r4-r11, r14}

    // TODO: write your code here

    pop {r4-r11, pc}